name: Build

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild .\PhysicsGame.sln /p:Configuration=Release

      - name: Create artifact directory
        run: mkdir -p artifact/PhysicsGame/

      - name: Copy the executable to the artifact directory
        run: cp path/to/your/executable artifact/PhysicsGame/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhysicsGame
          path: artifact/PhysicsGame/
